<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30" started-at="2022-11-21T05:35:45Z" finished-at="2022-11-21T05:35:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30" started-at="2022-11-21T05:35:45Z" finished-at="2022-11-21T05:35:45Z">
      <class name="test.test1">
        <test-method status="PASS" signature="printdata()[pri:0, instance:test.test1@36c88a32]" name="printdata" duration-ms="7" started-at="2022-11-21T05:35:45Z" finished-at="2022-11-21T05:35:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printdata -->
        <test-method status="PASS" signature="testcase2()[pri:0, instance:test.test1@36c88a32]" name="testcase2" duration-ms="1" started-at="2022-11-21T05:35:45Z" finished-at="2022-11-21T05:35:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method status="FAIL" signature="testcase3()[pri:0, instance:test.test1@36c88a32]" name="testcase3" duration-ms="0" started-at="2022-11-21T05:35:45Z" finished-at="2022-11-21T05:35:45Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at test.test1.testcase3(test1.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
      </class> <!-- test.test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
